name: timenotetracker
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #backend
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  google_sign_in: ^6.1.4
  #localDB
  drift: ^2.9.0
  sqlite3_flutter_libs: ^0.5.7
  path: ^1.8.0
  path_provider: ^2.0.10

  #fronted
  cupertino_icons: ^1.0.2
  responsive_framework: ^1.1.0
  concentric_transition: ^1.0.2
  lottie: ^2.4.0
  salomon_bottom_bar: ^3.3.1
  material_floating_search_bar_2: ^0.5.0
  
  #utils
  auto_route: ^5.0.1  
  injectable: ^2.1.2
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.0.1
  internet_connection_checker: ^1.0.0+1
  dartz: ^0.10.1
  uuid: ^3.0.6
  flutter_quill: ^7.2.4
  flutter_markdown: ^0.6.10+1
  rxdart: ^0.27.4
  

dev_dependencies:

  auto_route_generator: ^5.0.2
  injectable_generator: ^2.1.6
  build_runner: ^2.1.10
  flutter_lints: ^2.0.1
  freezed: ^2.0.2
  drift_dev: 
  mockito: 
flutter:
  uses-material-design: true

  assets:
    - assets/lottie/.
    - assets/mdFiles/.

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
