name: Build Production Apk
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Tests"]
    branches: [main]
    types: 
      - completed

jobs:
  flutter_build_apk:
    name: Build Production Flutter Apk
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.1'
      - run: flutter pub get
      - run: flutter build apk --flavor prod -t lib/main_prod.dart 
      - name: Upload APK
        uses: actions/upload-artifact@master
        with:
          name: apk-build
          path: build/app/outputs/apk/prod/app-prod.apk
       
      